# Generated by Django 6.0.1 on 2026-01-27 19:47

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_audio', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/musicas/'), upload_to='musicas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('duracao', models.IntegerField(default=0, help_text='Duração em segundos')),
                ('publica', models.BooleanField(default=False, help_text='Disponível para outros usuários')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=200)),
                ('vezes_tocada', models.IntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ultima_reproducao', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas_estudo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ordem_reproducao', models.CharField(choices=[('sequencial', 'Sequencial'), ('aleatoria', 'Aleatória'), ('repetir', 'Repetir Única')], default='sequencial', max_length=20)),
                ('cor_fundo', models.CharField(default='#3498db', help_text='Cor em hex (#RRGGBB)', max_length=7)),
                ('icone', models.CharField(default='fas fa-music', max_length=50)),
                ('musicas', models.ManyToManyField(blank=True, related_name='playlists', to='pomodoro_app.musicaestudo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_estudo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica', models.CharField(choices=[('pomodoro', 'Técnica Pomodoro Clássica'), ('personalizado', 'Técnica Personalizada')], default='pomodoro', max_length=20)),
                ('modalidade', models.CharField(choices=[('foco', 'Foco Total'), ('revisao', 'Revisão'), ('pratica', 'Prática'), ('leitura', 'Leitura')], default='foco', max_length=20)),
                ('tempo_foco', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('tempo_pausa_curta', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('tempo_pausa_longa', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('ciclos_para_pausa_longa', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('ciclos_completados', models.IntegerField(default=0)),
                ('tempo_total_estudado', models.IntegerField(default=0)),
                ('em_andamento', models.BooleanField(default=False)),
                ('som_notificacao', models.BooleanField(default=True)),
                ('notificacao_desktop', models.BooleanField(default=True)),
                ('tocar_musica', models.BooleanField(default=False)),
                ('volume_musica', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('loop_musica', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('musica_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_ativas', to='pomodoro_app.musicaestudo')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_pomodoro', to='pomodoro_app.playlistestudo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('foco', 'Em Foco'), ('pausa_curta', 'Pausa Curta'), ('pausa_longa', 'Pausa Longa'), ('completo', 'Completo'), ('pausado', 'Pausado')], default='foco', max_length=20)),
                ('ciclo_numero', models.IntegerField(default=1)),
                ('tempo_inicio', models.DateTimeField()),
                ('tempo_fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_restante', models.IntegerField()),
                ('distracoes', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('pomodoro_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='pomodoro_app.pomodorosession')),
            ],
            options={
                'ordering': ['-tempo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('meta_minutos', models.IntegerField(default=120)),
                ('minutos_estudados', models.IntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user', 'data')},
            },
        ),
    ]
